# Config file .travis.yml
language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo""
  
install:
  - pip install flake8
  - git clone https://github.com/CompassionCH/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  

script:
  - travis/travis_header.sh
  - travis_run_tests

notifications:
  email: false
  
after-success:
  - coveralls
